### PR TITLE
Updating to build-push-action-v2.2.2

### PR DESCRIPTION
**Pull request by jkennedyvz**
A lot of changes were needed to migrate for dependabot/github_actions/docker/build-push-action-v2.2.2 

This PR flattens the working changes from that branch.

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by jrozner** [comment]
Is this setup to tag `latest` from master?

**Comment by jkennedyvz** [comment]
> Is this setup to tag `latest` from master?

No actually, by default the action used will tag :latest if semver tagging is used https://github.com/crazy-max/ghaction-docker-meta#latest-tag

If we would like each run of this workflow to tag :latest I can add that manually on lines 72,103, and 134.

**Comment by jkennedyvz** [comment]
Everything in this PR has been implemented in #254 instead. Leaving this open until #254 is closed for comment reference.

**Comment by jkennedyvz** [comment]
Closing with the merge of #254

**Pull request closed without merging**
