### PR TITLE
remove access to operations via ID

### PR DESCRIPTION
**Pull request by JoelAtDeluxe**
This PR removes the outdated code and endpoints to access operations by ID (instead of by slug).

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by jrozner** [comment]
We should also be able to remove https://github.com/theparanoids/ashirt-server/blob/master/backend/dtos/dtos.go#L47-L50. Do you know if ashirt or aterm still use this? Do we need to make any change to them?

**Comment by JoelAtDeluxe** [comment]
Oh, forgot about this. No, those two both use slugs only in their network requests. I don't think they would use the IDs for any other purposes. I'll add that bit to this PR, and check out those two a bit closer to see if IDs are ever used for operations.

**Comment by JoelAtDeluxe** [comment]
We need to make a minor change to ashirt before we can merge this change. When we parse operations in the ashirt app, we parse (but don't use) the id field. So, we need to remove that, and then we should be good to go. I'll open up a PR for that soon.

**Comment by JoelAtDeluxe** [comment]
As a note, this PR should only be merged once this minor AShirt PR is merged:
https://github.com/theparanoids/ashirt/pull/112

**Review by jkennedyvz — APPROVED** [review]

**Pull request merged**
