### PR TITLE
Add help text for search bar

### PR DESCRIPTION
**Pull request by JoelAtDeluxe**
Adds help text for the search bar. The help icon is the question mark located _inside_ the search text bar. Clicking the icon will open a modal with a lengthy amount of help text to inform how to use the filtering features for  searching the timeline.

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by jkennedyvz — APPROVED** [review]
Hi @JoelAtDeluxe 

This help box looks great, thanks for the addition.

**Review by jrozner — CHANGES_REQUESTED** [review]
1. It looks like the esc key doesn't close the modal like the others, can we fix that?
2. This isn't super important but the evidence modal can pop up over the help modal and I've noticed this sort of behavior across other modals. Is there a consistent ordering of which modals can pop over which? Does it make sense revisit this later?
3. Is there a specific ordering currently for the various options? Should we alphabetize them?

**Comment by JoelAtDeluxe** [comment]
> 1. It looks like the esc key doesn't close the modal like the others, can we fix that?
Oops. Yes, I'll fix that.

> 2. This isn't super important but the evidence modal can pop up over the help modal and I've noticed this sort of behavior across other modals. Is there a consistent ordering of which modals can pop over which? Does it make sense revisit this later?
There is no defined order. What happens is that every modal gets appended to the DOM, and whatever is last is on top. We can force an order if this is a problem. 

> 3. Is there a specific ordering currently for the various options? Should we alphabetize them?
No specific ordering -- just matches what we have on the go side, which would be roughly in order of when the filter capabilities were expanded. I don't know if alphabetical is the right order here, as it kind of hides (what I presume are) more commonly used filter options. I'll take a stab at what I think is the most used ordering, but I'm happy to switch this to alphabetical if you think that'll be easier or more maintainable.

| Alphabetical | Joel's Suggestion |
| --- | --- |
| linked     | tag |
| operator | operator |
| range     | range |
| sort        | sort |
| tag         | linked |
| uuid        | with-evidence|
| with-evidence | uuid |

Also, looking at this list, we might want to introduce a new filter option: content type

**Review by jrozner — APPROVED** [review]

**Comment by jrozner** [comment]
Changes look good

**Pull request merged**
