### PR TITLE
Remove gantt chart overview

### PR DESCRIPTION
**Pull request by TylerNoblett**
Removed the operation overview (gantt chart) from the frontend and backend

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by JoelAtDeluxe — COMMENTED** [review]
Looks good.

**Comment by jrozner** [comment]
Is it safe to remove the react-calendar-timeline dependency within this PR?

**Comment by JoelAtDeluxe** [comment]
Yes, you should be able to drop react-calendar-timeline. it was only used in the operation_overview component.

**Comment by TylerNoblett** [comment]
removed `react-calendar-timeline` - good catch!

**Review by jkennedyvz — DISMISSED** [review]

**Comment by jkennedyvz** [comment]
@TylerNoblett can we re-base this now that we've merged the other updates to main?

**Comment by TylerNoblett** [comment]
@jkennedyvz I ran `git rebase main`, and the history looked like what we wanted, but when I went to push my changes to the remote, it also pulled some changes, and now there are 11 commits (some in main, some duplicates, and a merge commit), which seems like not what we want. I've rarely used rebase, mostly used merge. Do I just need to remove the commits that were added, and then force push my rebased branch?

**Comment by TylerNoblett** [comment]
@jkennedyvz I'm assuming my changes were correct, so this should be ready for merge - let me know if not

**Pull request merged**
